config/routes.rb
Rails.application.routes.draw do
  resources :sectors
  resources :industries 
  resources :industries_sectors
  
  resources :appointments
  get 'welcome/index'
  resources :physicians
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/sector.rb
class Sector < ApplicationRecord
    has_and_belongs_to_many :industries
    validates :name,uniqueness: { message: ->(object, data) do
        " must be unique, #{object.name}!, #{data[:value]} is taken already!  "end 
        }
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: %i[ show edit update destroy ]

  # GET /sectors or /sectors.json
  def index
    @sectors = Sector.all
  end

  # GET /sectors/1 or /sectors/1.json
  def show
    @industry =  @sector.industries
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors or /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to sector_url(@sector), notice: "Sector was successfully created." }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1 or /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to sector_url(@sector), notice: "Sector was successfully updated." }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1 or /sectors/1.json
  def destroy
    @sector.destroy

    respond_to do |format|
      format.html { redirect_to sectors_url, notice: "Sector was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sector_params
      params.require(:sector).permit(:name)
    end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/sectors/_form.html.erb
<%= form_with(model: sector) do |form| %>
  <% if sector.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
        <% sector.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sectors/_sector.html.erb
<div id="<%= dom_id sector %>">
 <tr>
  <td>  <%= sector.name %> </td>
   <td>  <%= link_to "Show ", sector %> </td>

  </tr>

</div>

app/views/sectors/edit.html.erb
<h1>Editing sector</h1>

<%= render "form", sector: @sector %>

<br>

<div>
  <%= link_to "Show this sector", @sector %> |
  <%= link_to "Back to sectors", sectors_path %>
</div>

app/views/sectors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sectors</h1>

<div id="sectors">
 <table border="1">
    <tr>
    <th>Name</th>
    <th>Show Industries</th>
    </tr>
  <% @sectors.each do |sector| %>
    <%= render sector %>
  <% end %>
   </table>
</div>

<%= link_to "New sector", new_sector_path %>

app/views/sectors/new.html.erb
<h1>New sector</h1>

<%= render "form", sector: @sector %>

<br>

<div>
  <%= link_to "Back to sectors", sectors_path %>
</div>

app/views/sectors/show.html.erb
<p style="color: green"><%= notice %></p>

<table border="1">
    <tr>
    <th>Industry Name</th>
    <th>Destroy Sector</th>
    </tr>
   <% @industry.each do |industry| %>
    <tr>
   <td> <%= industry.name %></td>
   <td>  <%= button_to "Destroy this Sector", industries_sector_path(sector_id: params[:id],industry_id: industry.id), method: :delete %> </td>

   </tr>
  <% end %>
   </table>
<div>
  <%= link_to "Back to sector", sectors_path %>

</div>