config/routes.rb
Rails.application.routes.draw do
  resources :sectors
  resources :industries 
  resources :industries_sectors
  
  resources :appointments
  get 'welcome/index'
  resources :physicians
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/physician.rb
class Physician < ApplicationRecord
     include Validatable
    has_many :appointments
    has_many :patients, through: :appointments
    before_validation :generate_unique_id

    private
    def generate_unique_id
        unique_id = Random.rand(100...999)

        while Physician.where(unique_id: unique_id).present? 
            unique_id = Random.rand(100...999)
            puts "#{unique_id} must be unique"
        end 
     
        puts unique_id
       
        self.unique_id = unique_id  

    end

    
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: %i[ show edit update destroy ]

  # GET /physicians or /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1 or /physicians/1.json
  def show
    @appointments = @physician.appointments

  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians or /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to physicians_path, notice: "Physician was successfully created." }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1 or /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to physicians_path, notice: "Physician was successfully updated." }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1 or /physicians/1.json
  def destroy
    @physician.destroy

    respond_to do |format|
      format.html { redirect_to physicians_url, notice: "Physician was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def physician_params
      params.require(:physician).permit(:name, :email, :unique_id)
    end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
<%= form_with(model: physician) do |form| %>
  <% if physician.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
        <% physician.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%# <%= form.label :unique_id, style: "display: block" %> 
    <%# <%= form.number_field :unique_id %> 
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/physicians/_physician.html.erb
<div id="<%= dom_id physician %>">

 <tr>
    <td> <%= physician.unique_id %></td>
    <td> <%= physician.name %></td>
    <td> <%= physician.email %></td>
    <td><%= link_to "Show", physician %></td>  
  </tr>
</div>

app/views/physicians/edit.html.erb
<h1>Editing physician</h1>

<%= render "form", physician: @physician %>

<br>

<div>
  <%= link_to "Show this physician", @physician %> |
  <%= link_to "Back to physicians", physicians_path %>
</div>

app/views/physicians/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Physicians</h1>
<%= link_to "New physician", new_physician_path %>
<br>
<br>
<br>
<div id="physicians">
 <table border="1">
    <tr>
    <th>Unique Id</th>
    <th>Name</th>
    <th>email</th>
    <th>Show Appointments</th>
    </tr>
   <% @physicians.each do |physician| %>
    <%= render physician %>
  <% end %>
</table>
  
</div>

app/views/physicians/new.html.erb
<h1>New physician</h1>

<%= render "form", physician: @physician %>

<br>

<div>
  <%= link_to "Back to physicians", physicians_path %>
</div>

app/views/physicians/show.html.erb
<p style="color: green"><%= notice %></p>

 <table border="1">
    <tr>
    <th>Patient Name</th>
    <th>Patient email</th>
    <th>Appointment Date</th>
    </tr>
   <% @appointments.each do |appointment| %>
    <tr>
   <td> <%= Patient.find(appointment.patient_id).name %></td>
   <td> <%= Patient.find(appointment.patient_id).email %></td>
    <td><%=appointment.appointment_date.to_time%></td>  
   </tr>
  <% end %>
   </table>
<div>
  <%= link_to "Edit this physician", edit_physician_path(@physician) %> |
  <%= link_to "Back to physicians", physicians_path %>

  <%= button_to "Destroy this physician", @physician, method: :delete %>
</div>