config/routes.rb
Rails.application.routes.draw do
  resources :sectors
  resources :industries 
  resources :industries_sectors
  
  resources :appointments
  get 'welcome/index'
  resources :physicians
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/industry.rb
class Industry < ApplicationRecord
    has_and_belongs_to_many :sectors
    include Validatable
    before_validation :generate_registration_number

    private
    def generate_registration_number
        registration_number = Random.rand(1000...9999)

        while Industry.where(registration_number: registration_number).present?  do
            registration_number = Random.rand(1000...9999)
            puts "#{registration_number} must be unique"

        end  
        puts registration_number

        self.registration_number = registration_number  

    end
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  before_action :set_industry, only: %i[ show edit update destroy ]

  # GET /industries or /industries.json
  def index
    @industries = Industry.all
  end

  # GET /industries/1 or /industries/1.json
  def show
    @sectors =  @industry.sectors
  end

  # GET /industries/new
  def new
    @industry = Industry.new
  end

  # GET /industries/1/edit
  def edit
  end

  # POST /industries or /industries.json
  def create
    @industry = Industry.new(industry_params)

    respond_to do |format|
      if @industry.save
        format.html { redirect_to industry_url(@industry), notice: "Industry was successfully created." }
        format.json { render :show, status: :created, location: @industry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /industries/1 or /industries/1.json
  def update
    respond_to do |format|
      if @industry.update(industry_params)
        format.html { redirect_to industry_url(@industry), notice: "Industry was successfully updated." }
        format.json { render :show, status: :ok, location: @industry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @industry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /industries/1 or /industries/1.json
  def destroy
    @industry.destroy

    respond_to do |format|
      format.html { redirect_to industries_url, notice: "Industry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_industry
      @industry = Industry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def industry_params
      params.require(:industry).permit(:name, :email, :registration_number)
    end

    def sector_params
      params.require(:industry).permit(:industry_id, :sector_id)
    end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_form.html.erb
<%= form_with(model: industry) do |form| %>
  <% if industry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(industry.errors.count, "error") %> prohibited this industry from being saved:</h2>

      <ul>
        <% industry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%# <%= form.label :registration_number, style: "display: block" %> 
    <%# <%= form.number_field :registration_number %> 
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/industries/_industry.html.erb
<div id="<%= dom_id industry %>">

<tr>   
<td>    <%= industry.name %></td>
<td>    <%= industry.email %></td>
<td>    <%= industry.registration_number %></td>
<td><%= link_to "Show ", industry %> </td>
</tr>   

</div>

app/views/industries/edit.html.erb
<h1>Editing industry</h1>

<%= render "form", industry: @industry %>

<br>

<div>
  <%= link_to "Show this industry", @industry %> |
  <%= link_to "Back to industries", industries_path %>
</div>

app/views/industries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Industries</h1>

<div id="industries">
<table border="1">
    <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Registration number</th>
    <th>Show Sectors</th>
  
    </tr>
  <% @industries.each do |industry| %>
    <%= render industry %>
  <% end %>
   </table>


</div>

<%= link_to "New industry", new_industry_path %>

app/views/industries/new.html.erb
<h1>New industry</h1>

<%= render "form", industry: @industry %>

<br>

<div>
  <%= link_to "Back to industries", industries_path %>
</div>

app/views/industries/show.html.erb
<p style="color: green"><%= notice %></p>

<table border="1">
    <tr>
    <th>Sector Name</th>
    <th>Destroy Sector</th>
    </tr>
   <% @sectors.each do |sector| %>
    <tr>
   <td> <%= sector.name %></td>
   <td>  <%= button_to "Destroy this Sector", industries_sector_path(industry_id: params[:id],sector_id: sector.id), method: :delete %> </td>

   </tr>
  <% end %>
   </table>
<div>
  <%= link_to "Back to industries", industries_path %>

</div>