config/routes.rb
Rails.application.routes.draw do
  resources :sectors
  resources :industries 
  resources :industries_sectors
  
  resources :appointments
  get 'welcome/index'
  resources :physicians
  resources :patients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :physician
  validates :appointment_date, presence: { message: " must be present" }

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]
  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
    @patients = Patient.all
    @physicians = Physician.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
    @patients = Patient.all
    @physicians = Physician.all
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    @patients = Patient.all
    @physicians = Physician.all
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:patient_id, :physician_id, :appointment_date)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>">
  <p>
    <strong>Patient:</strong>
    <%= appointment.patient_id %>
  </p>

  <p>
    <strong>Physician:</strong>
    <%= appointment.physician_id %>
  </p>

  <p>
    <strong>Appointment date:</strong>
    <%= appointment.appointment_date %>
  </p>

</div>

app/views/appointments/_form.html.erb
<div style="background-color:#F0FFFF; padding:50px; margin:10px; ">

<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :patient_id, style: "display: block" %>
    <%= form.select(:patient_id, options_for_select(@patients.all.map { |u| [u.name, u.id]}) ) %>
  </div>

  <div>
    <%= form.label :physician_id, style: "display: block" %>
    <%= form.select(:physician_id, options_for_select(@physicians.all.map { |u| [u.name, u.id]}) ) %>

  </div>

  <div>
    <%= form.label :appointment_date, style: "display: block" %>
    <%= form.datetime_field :appointment_date %>
  </div>
  <br>
  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render "form", appointment: @appointment %>

<br>

<div>
  <%= link_to "Show this appointment", @appointment %> |
  <%= link_to "Back to appointments", appointments_path %>
</div>

app/views/appointments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Appointments</h1>

<div id="appointments">
  <% @appointments.each do |appointment| %>
    <%= render appointment %>
    <p>
      <%= link_to "Show this appointment", appointment %>
    </p>
  <% end %>
</div>

<%= link_to "New appointment", new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render "form", appointment: @appointment %>

<br>

<div>
  <%= link_to "All appointments", appointments_path %>
</div>

app/views/appointments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @appointment %>

<div>
  <%= link_to "Edit this appointment", edit_appointment_path(@appointment) %> |
  <%= link_to "Back to appointments", appointments_path %>

  <%= button_to "Destroy this appointment", @appointment, method: :delete %>
</div>